dist: trusty
language: scala
scala:
  - 2.12.12
jdk:
  - oraclejdk11
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll
  - sbt ++$TRAVIS_SCALA_VERSION clean compile
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION 'set test in assembly := {}' assembly
before_deploy:
  - git config --local user.name "opentargets-admin"
  - git config --local user.email "administrator@opentargets.org"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file:
    - "target/scala-2.12/io-opentargets-etl-backend-assembly-*"
  on:
    repo: opentargets/platform-etl-backend
    tags: true
    all_branches: false

