name: build-dev

on:
  push:
    tags:
      # Matches tags that contain a dash after YY.major.minor
      # Example: 25.0.0-beta.1
      # Keep in mind github does not support all regex features:
      # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  upload-to-bucket:
    name: Build docker image and upload to a Google Cloud Storage bucket
    runs-on: ubuntu-22.04

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    env:
      TAG: ${{ github.ref_name }}
      REPO: ${{ github.event.repository.name }}
      SCALA_VERSION: 2.12.12
      OUTPUT_PATH: target/scala-2.12

    steps:
      - id: prepare
        name: Prepare the action and log details
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          TAG=$(echo $TAG | sed 's/^v//')
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "The tag for this build is $TAG"
          echo "The repo name is: $REPO"
          echo "Github context:\n$GITHUB_CONTEXT"

      - id: checkout
        name: Check out repo
        uses: actions/checkout@v4

      # =========== BUILD STEPS (TODO:  Extract to another workflow) ===========
      - id: scala-setup
        name: Install Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.11

      - id: cache
        name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/coursier
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - id: linter
        name: Lint code
        run: sbt ++${{ env.SCALA_VERSION }} scalafmtCheckAll

      - id: compile
        name: Compile code
        run: sbt ++${{ env.SCALA_VERSION }} clean compile

      - id: test
        name: Run tests
        run: sbt ++${{ env.SCALA_VERSION }} coverage test coverageReport

      - id: assembly
        name: Build jar
        run: sbt ++${{env.SCALA_VERSION }} 'set test in assembly := {}' assembly

      - id: rename
        name: Rename jar
        run: mv ${{ env.OUTPUT_PATH }}/etl-backend-*.jar ${{ env.OUTPUT_PATH }}/etl-backend-${{ env.TAG }}.jar
      # ========================================================================

      - id: auth-google
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: 'open-targets-eu-dev'
          workload_identity_provider: projects/426265110888/locations/global/workloadIdentityPools/github-actions/providers/opentargets
          service_account: github-actions@open-targets-eu-dev.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - id: upload-jar
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: ${{ env.OUTPUT_PATH }}/etl-backend-${{ env.TAG }}.jar
          destination: 'opentargets-pipelineg/etl/etl-backend-${{ env.TAG }}.jar'
